---
plugin: aws_ec2
regions:
  - ap-south-1

# Manage the access with IAM role attached to the Ansible master server
# aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
# aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>
keyed_groups:
  - key: tags
    prefix: tag

compose:
  ansible_host: private_ip_address