# code: language=yaml
---
- name: Initialize K8S Cluster
  hosts: tag_Type_MASTER
  become: yes
  remote_user: ubuntu
  roles:
    - role: k8s_master
      cluster_pod_cidr: "10.0.0.0/24"
      api_server_ip: "10.0.2.138"
