# code: language=yaml
---
- name: Install CNI pulugin
  hosts: tag_Type_MASTER
  remote_user: ubuntu
  tasks:
    - name: Install WeaveNet CNI plugin
      ansible.builtin.shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    # - name: Download WeaveNet CNI plugin 
    #   ansible.builtin.shell: wget /tmp/weave-daemonset-k8s.yaml https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml