---
- name: Join the Kubernetes Cluster 
  hosts: tag_Type_WORKER
  become: yes
  remote_user: ubuntu
  vars:
      master_host: "10.0.2.138"
      api_port : "6443"
      token_id : "ylp7ww.0xy31uhsq52lzo2v"
      cert_hash : "sha256:2efb285ffb933cba5e2cf26d4ad457eb385e8b2cb5fcac6437205650d83dd977"
  roles:
    - k8s-woker