---
- name: sysctl params required by setup, params persist across reboots
  ansible.builtin.copy:
    src: /home/cloudshell-user/k8s_infra/ansible/roles/k8s-master/vars/1k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes