---
- name: Initialize the Kubernetes cluster with provided variables
  ansible.builtin.script: ../files/cluster.sh "10.0.0.0/24" "10.0.2.87"
  args:
    executable : /bin/bash
  register: initialize_result

- name: Show the std putput 
  debug:
    var: initialize_result.stdout